[build]
  base = ""
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/acorn/"
  to = "/acorn/2.x/installation/"
  status = 302
  force = true

[[redirects]]
  from = "/bedrock/"
  to = "/bedrock/master/installation/"
  status = 301
  force = true

[[redirects]]
  from = "/examples/"
  to = "/examples/roots-example-project/"
  status = 301
  force = true

[[redirects]]
  from = "/sage/"
  to = "/sage/10.x/installation/"
  status = 302
  force = true

[[redirects]]
  from = "/sage/8.x/"
  to = "/sage/8.x/installation/"
  status = 301
  force = true

[[redirects]]
  from = "/sage/9.x/"
  to = "/sage/9.x/installation/"
  status = 301
  force = true

[[redirects]]
  from = "/trellis/"
  to = "/trellis/master/installation/"
  status = 301
  force = true

[[redirects]]
  from = "/trellis-cli/"
  to = "/trellis-cli/master/installation/"
  status = 301
  force = true

[[redirects]]
  from = "/sage/10.x/error-handling/"
  to = "/acorn/2.x/error-handling/"
  status = 301
  force = true

[[redirects]]
  from = "/sage/10.x/logging/"
  to = "/acorn/2.x/logging/"
  status = 301
  force = true

[[redirects]]
  from = "/acorn/2.x/what-is-acorn/"
  to = "/acorn/2.x/installation/"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/macos/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/ubuntu-linux/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/windows/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/trellis-cli/master/installation/"
  to = "/trellis/master/installation/"
  status = 301
  force = true

[[redirects]]
  from = "/trellis-cli/master/shell-integration/"
  to = "/trellis/master/installation/"
  status = 301
  force = true

[[redirects]]
  from = "/trellis-cli/master/virtualenv/"
  to = "/trellis/master/installation/"
  status = 301
  force = true

[[redirects]]
  from = "/sage/10.x/installing-packages/"
  to = "/acorn/2.x/installing-packages/"
  status = 301
  force = true

[[redirects]]
  from = "/sage/10.x/available-packages/"
  to = "/acorn/2.x/available-packages/"
  status = 301
  force = true

[[redirects]]
  from = "/sage/10.x/package-development/"
  to = "/acorn/2.x/package-development/"
  status = 301
  force = true
